### ISSUE TITLE
Kopano in Docker

### ISSUE THREAD

**Issue by fbartels** [nupplaphil/kopano-ldap#1]
Hi,

I've seen that you also have a fork (or an older version of) https://github.com/zokradonh/kopano-docker. If you want to work on some Docker images I would rather encourage you to take a look at the other project again, as there is a chance that this will later form the base for official kopano docker containers.

Greetings

**Comment by nupplaphil** [comment]
Hi,

Thanks for the hint! This repo is for a `kopano-ldap` CLI which will allow user-management for LDAP like the `kopano-cli` for the DB backend and a LDAP docker-image where I can use it.

But of course it would be better to have more people working on a docker environment for kopano .. I'll have a look :-)

Is it realistic to have **official** docker images for kopano? I think this is something kopano is avoiding because of their partnership with univention.

**Comment by fbartels** [comment]
Ah, ok. Then I have misinterpreted the "including a Docker image".

No, Univention does not have anything to do with the abstinence of official Docker images for Kopano. Maybe even slightly then opposite.

Creating good and universally usuable Containers is simply quite a lot of work. I started contributing to the linked project, since I wanted to have a good base for the upcoming rest  API app for Univention.
